import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-amber-50 min-h-screen px-6 py-3 flex flex-col gap-16">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
